--USE muitos_dados_omg

--					DESAFIO 1

--ALTER FUNCTION fnVolumeUltrapassado (@Data VARCHAR(7))

--RETURNS TABLE AS

--RETURN
--(
--	SELECT
--		TC.CPF, 
--		TC.NOME, 
--		TC.VOLUME_DE_COMPRA, 
--		@Data as 'DATA_mês',
--		SUM(IT.QUANTIDADE) AS 'QUANTIDADE_TOTAL', 

--	CASE WHEN 
--		SUM(IT.QUANTIDADE) > VOLUME_DE_COMPRA THEN 'VENDAS INVÁLIDAS'
--		ELSE 'VENDAS VÁLIDAS'

--		END AS 'RESULTADO'

--	FROM TABELA_DE_CLIENTES AS TC
--	INNER JOIN NOTAS_FISCAIS AS NF ON TC.CPF = NF.CPF
--	INNER JOIN ITENS_NOTAS_FISCAIS AS IT ON NF.NUMERO = IT.NUMERO

--	--WHERE CONVERT(NVARCHAR, NF.DATA_VENDA, 120) = @Data

--	WHERE 
--		--DATEPART(YEAR, NF.DATA_VENDA) = CAST(SUBSTRING(@Data, 1, 4) AS INT) AND 
--		--DATEPART(MONTH, NF.DATA_VENDA) = CAST(SUBSTRING(@Data, 7, 7) AS INT)

--		nf.DATA_VENDA LIKE @Data + '%'
	
--	GROUP BY TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA

--)

--SELECT * FROM fnVolumeUltrapassado('2015-01') ORDER BY CPF

--					DESAFIO 2

ALTER FUNCTION fnVendasTotais(@DATE DATETIME, @QTD INT)
RETURNS FLOAT AS
BEGIN
	RETURN 
	(
		SELECT
			CAST(@QTD AS FLOAT) / SUM(IT.QUANTIDADE) * 100 

		FROM NOTAS_FISCAIS AS NF 
		INNER JOIN ITENS_NOTAS_FISCAIS AS IT ON NF.NUMERO = IT.NUMERO
		INNER JOIN TABELA_DE_PRODUTOS AS TP ON IT.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO

		WHERE YEAR(NF.DATA_VENDA) = YEAR(@DATE) 
	)
END

ALTER FUNCTION fnSucoPorAno(@DATE DATETIME)

RETURNS TABLE AS 

RETURN
(
	SELECT 
		TP.SABOR, 
		SUM(IT.QUANTIDADE) AS 'VENDA_ANO',
		dbo.fnVendasTotais(@Date, SUM(IT.QUANTIDADE)) as 'PORCENTAGEM'

	FROM NOTAS_FISCAIS AS NF 
	INNER JOIN ITENS_NOTAS_FISCAIS AS IT ON NF.NUMERO = IT.NUMERO
	INNER JOIN TABELA_DE_PRODUTOS AS TP ON IT.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO

	WHERE YEAR(NF.DATA_VENDA) = YEAR(@DATE)

	GROUP BY TP.SABOR

)

SELECT * FROM fnSucoPorAno('2015-01-01') ORDER BY VENDA_ANO DESC


SELECT 
	*,
	ROUND(CAST(VENDA_ANO AS FLOAT) / (
		SELECT
			SUM(IT.QUANTIDADE)

		FROM NOTAS_FISCAIS AS NF 
		INNER JOIN ITENS_NOTAS_FISCAIS AS IT ON NF.NUMERO = IT.NUMERO
		INNER JOIN TABELA_DE_PRODUTOS AS TP ON IT.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO

		WHERE YEAR(NF.DATA_VENDA) = YEAR('2015-01-01')
		) * 100, 2) AS PERCENTUAL
FROM 
(
	SELECT
		TP.SABOR, 
		SUM(IT.QUANTIDADE) AS 'VENDA_ANO'

	FROM NOTAS_FISCAIS AS NF 
	INNER JOIN ITENS_NOTAS_FISCAIS AS IT ON NF.NUMERO = IT.NUMERO
	INNER JOIN TABELA_DE_PRODUTOS AS TP ON IT.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO

	WHERE YEAR(NF.DATA_VENDA) = YEAR('2015-01-01')

	GROUP BY TP.SABOR

) AS B
ORDER BY VENDA_ANO DESC