# CREATE DATABASE db_da_kau;

SHOW DATABASES;

USE db_da_kau;

# CREATE TABLE Aluno (
	#IDAluno INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    #Nome VARCHAR(20),
    #Sobrenome VARCHAR(12)
    
#) DEFAULT CHARSET UTF8;

SELECT ALL Aluno;

CREATE TABLE Professor (
	IDProfessor INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    Nome VARCHAR(20),
    Sobrenome VARCHAR(12)
    
) DEFAULT CHARSET UTF8;