CREATE DATABASE ex5_prova;

# DROP TABLE Pessoa, Endereco, Telefone;

USE ex5_prova;

CREATE TABLE Pessoa (
	
	IDPessoa INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
    Nome VARCHAR(30) NOT NULL,
	IDEndereco INT NOT NULL,
    FOREIGN KEY (IDEndereco) REFERENCES Endereco(IDEndereco)
    
);

CREATE TABLE Endereco (
	
	IDEndereco INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
    Cidade VARCHAR(30) NOT NULL, 
    Estado VARCHAR(2) NOT NULL
);

CREATE TABLE Telefone (

	IDTelefone INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
    Telefone VARCHAR(15) NOT NULL, 
    IDPessoa INT NOT NULL,
	FOREIGN KEY (IDPessoa) REFERENCES Pessoa(IDPessoa)
);

